# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/claudette-pydantic',
                'doc_host': 'https://tom-pollak.github.io',
                'git_url': 'https://github.com/tom-pollak/claudette-pydantic',
                'lib_path': 'claudette_pydantic'},
  'syms': { 'claudette_pydantic.struct': { 'claudette_pydantic.struct.BaseModel.claude_schema': ( 'struct.html#basemodel.claude_schema',
                                                                                                  'claudette_pydantic/struct.py'),
                                           'claudette_pydantic.struct.Chat.struct': ( 'struct.html#chat.struct',
                                                                                      'claudette_pydantic/struct.py'),
                                           'claudette_pydantic.struct.Client.struct': ( 'struct.html#client.struct',
                                                                                        'claudette_pydantic/struct.py'),
                                           'claudette_pydantic.struct._escape_json_newlines': ( 'struct.html#_escape_json_newlines',
                                                                                                'claudette_pydantic/struct.py'),
                                           'claudette_pydantic.struct._mk_struct': ( 'struct.html#_mk_struct',
                                                                                     'claudette_pydantic/struct.py')}}}
